swapTextureFlag = 0x80090170;
swapTexturePointer = 0x1F800044;

backupClut = 0x8009F870;

CutsceneLayoutPointers = 0x800ebb1c;
CreateTitleScreenThread = 0x8001e69c;

clutPointer = 0x1F800028;
clutRect = 0x8006fa1c;

enemyDataPointers = 0x80074b58;
ExitBranch = 0x80034630;
exitType = 0x800e4800;
exitStage = 0x800e4801;

FlushScreen = 0x80027eac;

title = 0x800ceab8;

LevelMidTable = 0x8007284c;
loadState = 0x8009675c;
LoadCompressedImage = 0x80018f3c;
LoadBossRefightsArc = 0x80015148;
LoadBackupScreens = 0x8001925c;

SwapWeaponTexturesClut = 0x80040690;

StageLayoutPointers = 0x80077994;

updateClut = 0x800c5c20;
