swapTextureFlag = 0x8008eab0;
swapTexturePointer = 0x1F800044;

backupClut = 0x8009e1b0;

CutsceneLayoutPointers = 0x800ea514;
CreateTitleScreenThread = 0x8001d25c;

clutPointer = 0x1F800028;
clutRect = 0x8006e360;

enemyDataPointers = 0x8007349c;
ExitBranch = 0x80033034;
exitType = 0x800e3140;
exitStage = 0x800e3141;

FlushScreen = 0x800268b0;

title = 0x800cd3f8;

LevelMidTable = 0x80071190;
loadState = 0x8009509c;
LoadCompressedImage = 0x80017b04;
LoadBossRefightsArc = 0x80013d10;
LoadBackupScreens = 0x80017e24;

SwapWeaponTexturesClut = 0x8003f0bc;

StageLayoutPointers = 0x800762e0;

updateClut = 0x800c4560;