swapTextureFlag = 0x8008eab0;
swapTexturePointer = 0x1F800044;

backupClut = 0x8009e1b0;

CutsceneLayoutPointers = 0x800ea514;
CreateTitleScreenThread = 0x8001d25c;

clutPointer = 0x1F800028;
clutRect = 0x8006e360;

enemyDataPointers = 0x8007349c;
ExitBranch = 0x80033034;
exitType = 0x800e3140;
exitStage = 0x800e3141;

FlushScreen = 0x800268b0;

title = 0x800cd3f8;

LevelMidTable = 0x80071190;
loadState = 0x8009509c;
LoadCompressedImage = 0x80017b04;
LoadBossRefightsArc = 0x80013d10;
LoadBackupScreens = 0x80017e24;

SwapWeaponTexturesClut = 0x8003f0bc;

StageLayoutPointers = 0x800762e0;

updateClut = 0x800c4560;

disableExtraFiles = 0x80097426;

GetPlayerMugShotId = 0x800228ac;

/*Level Related Addresses*/
LevelOvlTable = 0x8006db78;
LevelFileTable = 0x8006d9fc;
X_ClutFileTable = 0x8006da88;
Zero_ClutFileTable = 0x8006dae4;
LevelTextFileTable = 0x8006dbd4;
NightmareTextFileTable = 0x8006dc30;
LevelLayoutSizeTable = 0x80076398;
LevelExtraFilesTable = 0x8006e174;
BossMugShotFileTable = 0x8006e1a4;
/*Object Function Pointer Tables*/
LevelMainObjectsFunction_Table = 0x8006dc6c;
LevelVisualObjectsFunction_Table = 0x8006dd24;
LevelShotObjectsFunction_Table = 0x8006dddc;
LevelEffectObjectsFunction_Table = 0x8006de94;
LevelMiscObjectsFunction_Table = 0x8006e004;
LevelItemObjectsFunction_Table = 0x8006df4c;
LevelQuadObjectsFunction_Table = 0x8006e0bc;