swapTextureFlag = 0x80090170;
swapTexturePointer = 0x1F800044;

backupClut = 0x8009F870;

CutsceneLayoutPointers = 0x800ebb1c;
CreateTitleScreenThread = 0x8001e69c;

clutPointer = 0x1F800028;
clutRect = 0x8006fa1c;

datFileInfo = 0x800e1a58;

enemyDataPointers = 0x80074b58;
ExitBranch = 0x80034630;
exitType = 0x800e4800;
exitStage = 0x800e4801;

FlushScreen = 0x80027eac;

title = 0x800ceab8;

textRects = 0x80102218;

LevelMidTable = 0x8007284c;
loadState = 0x8009675c;
LoadCompressedImage = 0x80018f3c;
LoadBossRefightsArc = 0x80015148;
LoadBackupScreens = 0x8001925c;

SwapWeaponTexturesClut = 0x80040690;

StageLayoutPointers = 0x80077994;

updateClut = 0x800c5c20;

disableExtraFiles = 0x80098ae6;

GetPlayerMugShotId = 0x80023d08;

/*Level Related Addresses*/
LevelOvlTable = 0x8006f25c;
LevelFileTable = 0x8006f0e0;
X_ClutFileTable = 0x8006f16c;
Zero_ClutFileTable = 0x8006f1c8;
LevelTextFileTable = 0x8006f2b8;
NightmareTextFileTable = 0x8006f314;
LevelLayoutSizeTable = 0x80077a4c;
LevelExtraFilesTable = 0x8006f858;
BossMugShotFileTable = 0x8006f888;
/*Object Function Pointer Tables*/
LevelMainObjectsFunction_Table = 0x8006f350;
LevelVisualObjectsFunction_Table = 0x8006f408;
LevelShotObjectsFunction_Table = 0x8006f4c0;
LevelEffectObjectsFunction_Table = 0x8006f578;
LevelMiscObjectsFunction_Table = 0x8006f6e8;
LevelItemObjectsFunction_Table = 0x8006f630;
LevelQuadObjectsFunction_Table = 0x8006f7a0;